name: seq-sel
version: 0.0
author: bnspalding
copyright: 2019 Ben Spalding
synopsis: project description for seq-sel

dependencies:
  - base >= 4.9 && < 5
  - optparse-applicative

executable:
  main: src/Main.hs

default-extensions: []
