# Some commonly used options have been documented as comments in this file.
# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

# Resolver to choose a 'specific' stackage snapshot or a compiler version.
# A snapshot resolver dictates the compiler version and the set of packages
# to be used for project dependencies. For example:
resolver: lts-14.2

packages:
  - seq-sel-main
  - Gen

ghc-options:
  "$locals": -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints

rebuild-ghc-options: true

extra-deps:
  - text-replace-0.0.0.4@sha256:88800aba160dfb512cf43b24063170d34900e1646ad21f28715a22679f42ae15,1738
  - github: bnspalding/sound
    commit: 00a9aa6b083293f0abcdf171d65708e7a9358061
  - github: bnspalding/dictionary
    commit: d7e52a679ae5f254acb08cb105e79349f86dafab
