name: Gen
version: 0.0
author: "bnspalding"
copyright: "Copyright (c) 2019 Ben Spalding"
synopsis: "project description for seq-sel/gen"

description: Please see the README on GitHub at <https://github.com/bnspalding/seq-sel#readme>

dependencies:
  - base >= 4.9 && < 5
  - Sound
  - containers

library:
  source-dirs: .

default-extensions: []
