name: seq-sel
version: 0.0
github: "bnspalding/seq-sel"
author: "bnspalding"
copyright: "Copyright (c) 2019 Ben Spalding"
license: "CC-BY-NC-ND-4.0"
synopsis: "project description for seq-sel"

description: Please see the README on GitHub at <https://github.com/bnspalding/seq-sel#readme>

dependencies:
  - base >= 4.9 && < 5
  - optparse-applicative
  - yaml
  - Gen
  - dictionary

executables:
  seq-sel:
    main: Main.hs
    other-modules: OptionsParsing
    source-dirs: src

tests:
  seq-sel-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec
      - hspec-discover

default-extensions: []
