name: Vector
version: 0.0
author: "bnspalding"
copyright: "Copyright (c) 2019 Ben Spalding"
synopsis: "project description for seq-sel/vector"

description: Please see the README on GitHub at <https://github.com/bnspalding/seq-sel#readme>

dependencies:
  - base >= 4.9 && < 5

library:
  source-dirs: src

default-extensions: []
