name: Gen
version: 0.0
author: "bnspalding"
copyright: "Copyright 2019 Ben Spalding"
license: "CC-BY-NC-4.0"
synopsis: "project description for seq-sel/gen"

description: Please see the README on GitHub at <https://github.com/bnspalding/seq-sel#readme>

dependencies:
  - base >= 4.9 && < 5
  - sound
  - dictionary
  - containers
  - text
  - vector

library:
  source-dirs: src

tests:
  Gen-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec
      - Gen

default-extensions: []
